### ISSUE TITLE
how to use GPU to compute?

### ISSUE THREAD

**Issue by Jian-danai** [Borda/pyImSegm#23]
I found that the computing process is slow, and no gpu is used. How to implement the training with gpu?

**Comment by Borda** [comment]
Thanks for your comment.
 Indeed there is no GPU used since it was considered moreless a research package.
I agree that some computation can be moved on GPU, on the other hand it is build on standard libraries so if you find and alternative with GPU the switch should not be hard...
May I ask what training do you have in mind? Computing features or fitting the classifier/model...

**Comment by blasco** [comment]
I'm struggling with the same issue, when texture metrics are used the training is too slow, and as said no GPU is used, it would be a great addition.

**Comment by Borda** [comment]
@blasco thank you cor your interest, unfortunately, this is not actively developed any more as it was my PhD project several years back, but any PR with improvement would be very welcome :rabbit:

**Comment by Borda** [comment]
@Jian-danai @blasco feel free to reopen if you want to implement such GPU extension :]
I agree that it would be great but do not have time to do it... maybe some application of [Kornia](https://github.com/kornia/kornia)?
